name: Build Fonts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
    
      - name: Install FontForge
        run: |
          sudo apt update
          sudo apt install -y fontforge python3-fontforge

      - name: Build fonts
        run: |
          fontforge -lang=py -script build.py

      - name: Upload built fonts
        uses: actions/upload-artifact@v7
        with:
          name: built-fonts
          path: dist/*.ttf